### ISSUE TITLE
WordPress database error: 

### ISSUE THREAD

**Issue by mamunur105** [sultann/wp-query-builder#4]
When I use $query object multiple time in a function
Please check [the screenshoot ](https://prnt.sc/uyf6fo)

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* FROM wp_incf_monthly_report wp_incf_monthly_report WHERE student_id = 3 and (' at line 1]
SELECT *,* FROM wp_incf_monthly_report wp_incf_monthly_report WHERE student_id = 3 and (date BETWEEN '2020-10-01' AND '2020-10-31') and (post_date BETWEEN '2020-10-01' AND '2020-10-31')

**Comment by sultann** [comment]
By default it's run on a single instance so more you add query argument that will be appended with the query.
If you want to call multiple times for multiple queries then either call $query->copy() from a fresh instance or make a new instance.

**Comment by mamunur105** [comment]
Thank you . 
Now i need to do something more . 
I need count some column unique data. in a single query . Duplicate value will ignore . 
Is it possible ?  


$query->select('count( DISTINCT  date ) as datecount')  Like that  ?
